### ISSUE TITLE
[Bug] Does not work well with resource pack fonts

### ISSUE THREAD

**Issue by Imzxhir** [Qendolin/BetterUIScale#3] opened 2023-09-20 21:04 UTC
Description: I tried to use a resource pack from [this modpack](https://github.com/Kichura/MCWine) which adds a resource pack font to make the font smooth. But, I found with this mod that the font that the resource pack adds looks really broken.

With the mod (GUI Scale 27):

![image](https://github.com/Qendolin/BetterUIScale/assets/98621617/0cea0159-d868-40d6-b83d-7ee48037972f)

Without the mod (GUI Scale 3):

![image](https://github.com/Qendolin/BetterUIScale/assets/98621617/84d34507-5030-4c3a-94a8-2295248a963a)

**Comment by Qendolin** [comment] 2023-09-20 21:18
I've noticed that the grass block in the background also looks weird in your first screenshot: 
![image](https://github.com/Qendolin/BetterUIScale/assets/32160662/cb909435-b61d-457e-a129-bfc17b8620d2)
The transition between the texels should be sharp, but this cannot possibly be caused by the mod. Can you also test version 1.1.0 with GUI Scale 300%?

**Comment by Imzxhir** [comment] 2023-09-20 21:26
Well, the resource pack does change the grass texture so it could be that but the max I can go is GUI Scale 49x so I will try that.

**Comment by Imzxhir** [comment] 2023-09-20 21:28
Here are the screenshots with GUI Scale 49:

![image](https://github.com/Qendolin/BetterUIScale/assets/98621617/7fbe5bde-4208-47c0-9d1e-4c477ca08b06)

**Comment by Qendolin** [comment] 2023-09-21 10:23
I think what I'll do is add a setting to disable the font rendering changes

**Comment by Qendolin** [comment] 2023-10-09 22:57
Version 1.2.0 adds an option to disable the font smoothing. I haven't tried it with a hi res font but I consider this fixed. Let me know if its still an issue.

**Comment by Qendolin** [comment] 2023-10-09 23:43
See #6

**Comment by Qendolin** [comment] 2023-10-10 13:10
Fixed in 1.2.1

**Closed by Qendolin** 2023-10-10 13:10 UTC
